### ISSUE TITLE
Unable to see the user after user federation

### ISSUE THREAD

**Issue by nmanthena18** [redarccoder/singular-keycloak-database-federation#1]
Thanks for SPI I am using 22.0.0 I have same requirement in my application, could you please assitance on the below issue.

I am getting this logs in the terminal 

```
2023-08-04 11:59:30,421 INFO  [com.zaxxer.hikari.HikariDataSource] (executor-thread-9) SINGULAR-USER-PROVIDER-keycloak04-08-2023 11:59:30 - Starting...
2023-08-04 11:59:30,430 INFO  [com.zaxxer.hikari.HikariDataSource] (executor-thread-9) SINGULAR-USER-PROVIDER-keycloak04-08-2023 11:59:30 - Start completed.
2023-08-04 11:59:30,436 INFO  [com.zaxxer.hikari.HikariDataSource] (executor-thread-9) SINGULAR-USER-PROVIDER-keycloak04-08-2023 11:59:26 - Shutdown initiated...
2023-08-04 11:59:30,442 INFO  [com.zaxxer.hikari.HikariDataSource] (executor-thread-9) SINGULAR-USER-PROVIDER-keycloak04-08-2023 11:59:26 - Shutdown completed.
```
and I am unable to see any user in the users menu including super admin (the user created at initial setup).

Thanks.

**Comment by redarccoder** [comment]
Hello, I just pushed a new version of this plugin. For some reason, if you add a parameter named "enabled" to the SPI, and, set a different value than "enabled" then it disables the SPI... I don't see any of this in any comment.

Please try the new version, you should the message of the extension being enabled.

If you have any other problem just let me know

**Comment by nmanthena18** [comment]
Still I am getting errors and I am unable to fetch the users below is my configuration.

![image](https://github.com/redarccoder/singular-keycloak-database-federation/assets/26927912/9297b7f4-c2e4-40da-bf89-8bbb67d40154)

![image](https://github.com/redarccoder/singular-keycloak-database-federation/assets/26927912/2c875522-43ca-4acd-9559-bd6710ef81af)

my query working in workbench but not in keycloak
![image](https://github.com/redarccoder/singular-keycloak-database-federation/assets/26927912/55c3c5d4-4e46-43a3-999e-357348219f0d)

its not working keycloak
![image](https://github.com/redarccoder/singular-keycloak-database-federation/assets/26927912/cd8e1e78-a166-4e2e-bf68-261bbde3a0cb)

this time I should get all the users including my external db user and keycloak users but got only keycloak user which my super admin

![image](https://github.com/redarccoder/singular-keycloak-database-federation/assets/26927912/cb63d587-f599-4620-8a07-c92e67b73d74)

If i hit the sync users its always showing **Synchronization ignored as it's already in progress.**

**Comment by redarccoder** [comment]
@nmanthena18 , can I close this issue?

**Comment by nmanthena18** [comment]
I will check and let you know and there is one more issue if you observe by default users are not loading after enabling this SPI

**Comment by redarccoder** [comment]
I think this is the default behavior from keycloak. You can test this by enabling LDAP deferation, it will not load any user by default.

It was different in Keycloak <19, I think some people had some massive UserFederations and it was causing problems for other users to login....

**Comment by MadhuPeddinti** [comment]
![Screenshot from 2023-08-31 16-42-541](https://github.com/redarccoder/singular-keycloak-database-federation/assets/35192857/6ad281a9-043e-4207-b3e0-814fec518cd1)
![Screenshot from 2023-08-31 16-43-121](https://github.com/redarccoder/singular-keycloak-database-federation/assets/35192857/1f05341a-d323-4bf3-b9f8-1647c85d4273)

@redarccoder I have created packages with your latest fix with `mvn clean package` and not able to fetch the user and got this error,

`2023-08-31 17:19:07,396 INFO  [org.opensingular.dbuserprovider.persistence.UserRepository] (executor-thread-19) RS: HikariProxyResultSet@1708990560 wrapping com.mysql.cj.jdbc.result.ResultSetImpl@57217a17
2023-08-31 17:19:07,410 INFO  [org.opensingular.dbuserprovider.model.UserAdapter] (executor-thread-19) IsEnabled: null
`
